@extends('layouts.app')

@section('title', 'Detalle almacén')

@section('page')
<div class="container-fluid">
    <div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="mb-1">{{ $warehouse->name }}</h1><p class="text-muted mb-0">Registro de ingresos y salidas del almacén.</p></div><div class="d-flex gap-2"><a href="{{ route('warehouses.edit', $warehouse) }}" class="btn btn-primary">Editar</a><a href="{{ route('warehouses.index') }}" class="btn btn-outline-secondary">Volver</a></div></div>
    <div class="row g-4">
        <div class="col-lg-4">
            <div class="card border-0 shadow-sm mb-4"><div class="card-body"><p><strong>Empresa:</strong> {{ $warehouse->company?->name }}</p><p><strong>Sucursal principal:</strong> {{ $warehouse->primaryBranch?->name ?: 'No asignada' }}</p><p><strong>Código:</strong> {{ $warehouse->code }}</p><p><strong>Ubicación:</strong> {{ $warehouse->location ?: '-' }}</p><p><strong>Descripción:</strong> {{ $warehouse->description ?: '-' }}</p></div></div>
            <div class="card border-0 shadow-sm"><div class="card-body"><h6 class="fw-bold mb-3">Nuevo movimiento</h6><form action="{{ route('warehouses.movements.store', $warehouse) }}" method="POST" class="row g-3">@csrf <div class="col-12"><label class="form-label">Producto</label><select name="product_id" class="form-select" required><option value="">Seleccionar</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }} ({{ $product->sku }})</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Tipo</label><select name="type" class="form-select" required><option value="in">Ingreso</option><option value="out">Salida</option></select></div><div class="col-md-6"><label class="form-label">Cantidad</label><input type="number" step="1" min="1" inputmode="numeric" name="quantity" class="form-control" required></div><div class="col-md-6"><label class="form-label">Costo unitario</label><input type="number" step="0.01" name="unit_cost" class="form-control"></div><div class="col-md-6"><label class="form-label">Fecha</label><input type="datetime-local" name="movement_date" class="form-control" value="{{ now()->format('Y-m-d\TH:i') }}" required></div><div class="col-12"><label class="form-label">Referencia</label><input type="text" name="reference" class="form-control"></div><div class="col-12"><label class="form-label">Notas</label><textarea name="notes" class="form-control" rows="3"></textarea></div><div class="col-12"><button class="btn btn-primary w-100" type="submit">Guardar movimiento</button></div></form></div></div>
        </div>
        <div class="col-lg-8">
            <div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h6 class="fw-bold mb-0">Historial de movimientos</h6><span class="badge bg-light text-dark">{{ $warehouse->inventoryMovements->count() }} movimientos</span></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Fecha</th><th>Producto</th><th>Tipo</th><th class="text-end">Cantidad</th><th class="text-end">Costo</th><th>Usuario</th></tr></thead><tbody>@forelse($warehouse->inventoryMovements as $movement)<tr><td>{{ $movement->movement_date?->format('d/m/Y H:i') }}</td><td>{{ $movement->product?->name ?: '-' }}</td><td><span class="badge {{ $movement->type === 'in' ? 'bg-success' : 'bg-warning text-dark' }}">{{ $movement->type === 'in' ? 'Ingreso' : 'Salida' }}</span></td><td class="text-end">{{ number_format($movement->quantity, 0) }}</td><td class="text-end">{{ money($movement->unit_cost ?? 0, null, 2) }}</td><td>{{ $movement->user?->name ?: '-' }}</td></tr>@empty<tr><td colspan="6" class="text-center py-5 text-muted">Sin movimientos registrados.</td></tr>@endforelse</tbody></table></div></div></div>
        </div>
    </div>
</div>
@endsection